config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end
  
  scope module: :public do
    resources :items, only: [:index, :show]
  end
  
  scope module: :public do
    get '/customers/confirm' => 'customers#confirm', as: 'confirm_customer'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    resources :customers, only: [:show, :edit, :update]
  end
  
  scope module: :public do
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  
  scope module: :public do
    post '/orders/confirm' => 'orders#confirm', as: 'confirm_order'
    get '/orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :create, :index, :show, :update]
  end
  
  scope module: :public do
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    get '/admin' => 'homes#top'
  end
  
  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end
  
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  
  namespace :admin do
    resources :orders, only: [:show, :update]
  end
  
  namespace :admin do
    resources :order_items, only: [:update]
  end
  
  namespace :admin do
    resources :genres, omly: [:create, :index, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  belongs_to :genre
end

app/models/opp.rb
class Opp < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update
    redirect_to admin_genres_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def new
    @item = Item.new
  end
  
  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end
  
  def index
    if params[:name]
      @items = Item.where(name params[:name])
    else
      @items = Item.all
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path
  end
  
  private 
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :is_status, :genre_id, :image)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/index.html.erb
<h3>ジャンル一覧・追加</h3>

<%= form_with model: @genre, url: admin_genres_path do |f| %>
  <p>ジャンル名</p>  <%= f.text_field :name %>. <%= f.submit '新規登録' %>
<% end %>

<table>
  <th>
    <tr>ジャンル</tr>
  </th>
    <% @genres.each do |genre| %>
    <th>
      <tr><%= genre.name %></tr>
      <tr><%= link_to "編集する", edit_admin_genre_path(genre.id) %></tr>
    </th>
    <% end %>
</table>

app/views/admin/items/edit.html.erb
<h3>商品編集</h3>

<table>
  <%= form_with model: @item,url:admin_item_path do |f| %>
  <tr>
    <td>商品画像</td>
    <td><%= f.file_field :image, accept:"image/*" %></td>
  </tr>
  <tr>
    <td>商品名</td>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td>商品説明</td>
    <td><%= f.text_area :introduction %></td>
  </tr>
  <tr>
    <td>ジャンル</td>
    <td><%= f.select :genre_id,  options_from_collection_for_select(Genre.all, :id, :name) %></td>
  </tr>
  <tr>
    <td>税抜価格</td>
    <td><%= f.text_field :price %></td>
  </tr>
  <tr>
    <td>販売ステータス</td>
    <td><%= f.radio_button :is_status, "販売中" %>  <%= f.radio_button :is_status, "販売停止中" %></td>
  </tr>
  <tr>
    <td><%= f.submit '変更を保存' %></td>
  </tr>
  <% end %>
</table>

app/views/admin/items/index.html.erb
<h3>商品一覧</h3>. <%= link_to "商品新規登録", new_admin_item_path %>

  <table>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %></td>
        <td><%= item.genre_id %></td>
        <td><%= item.is_status %></td>
      </tr>
    <% end %>
  </table>

app/views/admin/items/new.html.erb
<h3>商品新規登録</h3>

<%= form_with model: @item,url: admin_items_path do |f| %>
<p>商品画像</p>. <%= f.file_field :image, accept:"image/*" %>
<p>商品名</p>. <%= f.text_field :name %>
<p>商品説明</p>. <%= f.text_area :introduction %>
<p>ジャンル</p>  <%= f.select :genre_id,  options_from_collection_for_select(Genre.all, :id, :name) %>
<p>税抜価格</p>  <%= f.text_field :price %>
<p>販売ステータス</p>. <%= f.radio_button :is_status, "販売中" %>  <%= f.radio_button :is_status, "販売停止中" %>
<%= f.submit '新規登録' %>
<% end %>

app/views/admin/items/show.html.erb
<h3>商品詳細</h3>
<%= image_tag @item.image, size: "100×100" %>
<table>
  <tr>
    <td>商品名</td>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <td>商品説明</td>
    <td><%= @item.introduction %></td>
  </tr>
  <tr>
    <td>ジャンル</td>
    <td><%= @item.genre_id %></td>
  </tr>
  <tr>  
    <td>税込価格<br>（税抜価格）</td>
    <td><%= @item.price.to_i*1.1 %>(<%= @item.price %>)</td>
  </tr>
  <tr>
    <td>販売ステータス</td>
    <td><%= @item.is_status %></td>
  </tr>
</table>

<%= link_to "編集する", edit_admin_item_path %>